### ISSUE TITLE
çeviri hatası

### ISSUE THREAD

**Issue by suvari** [PisiLinuxNew/package-manager#10]
pm de bir çeviri hatası var.
sistemtry daki pm yi sağ tıklayınca çıkıyor: ... güncelleniyor değil,  güncelle olmalı, küçük harflerle de olur, "pisi deposunu güncelle" vaya, "Pisi deposunu güncelle" olabilir,  "Depo Güncelleniyor" yerine, "tüm depoları güncelle" gibi bişi olmalı
http://i.hizliresim.com/ljAyZX.png

**Comment by hrngultekin** [comment]
düzeltildi
