### ISSUE TITLE
icon hatası

### ISSUE THREAD

**Issue by alihanozturk** [PisiLinuxNew/package-manager#11]
.desktop dosyalarında   Icon=application-x-pisi   yazıyor. paket yöneticisinin menu iconları bu sebeple görünmüyor. package-manager.png nereye atılıyorsa oranın yolu verilmelidir.

setup.py dosyasında

 icon_dir = os.path.join(root_dir, "icons/{}/apps/128".format(theme_name))

bölümü /usr/share/pixmaps 

yapılıp .desktop dosyalarında icon bölümüne eklenebilir.

**Comment by mthnzbk** [comment]
https://github.com/PisiLinuxNew/package-manager/commit/b9bd9527728515940d8d02fc66b04fbf25451f4b ile çözüldü.
