### ISSUE TITLE
paket arama satırı

### ISSUE THREAD

**Issue by suvari** [PisiLinuxNew/package-manager#20]
package-manager, paket adını yazdığımız yeri mouse ile seçip silmekle, kendini yenilemiyor
illaki yandaki siyah çarpılı yeri tıklayıp, sonra yeni paket adını yazmak gerekiyor, aksi takdirde ilgili paketi bulamıyor.

sanırım hata şu:   " parent ögesinin cleanUp özelliği yok."

vaktin olunca bakabilir misin üstad,
bu özellik, qt5 port öncesi sağlamdı, sanırım bir eksiklik var.. 
teşekkürler, iyi çalışmalar...

**Comment by hrngultekin** [comment]
sorun çözüldü
