### ISSUE TITLE
Package-Manager-Desktop

### ISSUE THREAD

**Issue by Rmys** [PisiLinuxNew/package-manager#22]
Başlatta Package-Manager-Desktop ingilizce olarak görünüyor

**Comment by Rmys** [comment]
[Desktop Entry]
Name=Package Manager
Name[tr]=Paket Yönetiçi
GenericName=Add or Remove Software **BEN BU SATIRI TÜRÇE YAPARAK KULLANIYORUM**
GenericName[tr]=Yazılım Ekle Kaldır
Comment=PiSi Package Manager Graphical User Interface
Comment[tr]=PiSi Paket Yöneticisi Grafik Kullanıcı Arayüzü 
Icon=application-x-pisi
Type=Application
Exec=package-manager --show-mainwindow
Categories=Qt;KDE;System;

**Comment by aydemir** [comment]
GenericName[tr]= ile cevirisini ekleyebilirsin

**Comment by ayhanyalcinsoy** [comment]
fixed with 4efaddf914e13d68ab632657ef256891ba9af2b7
