### ISSUE TITLE
daha fazla uygulama kur kdeinit hatası veriyor

### ISSUE THREAD

**Issue by aydemir** [PisiLinuxNew/package-manager#7]
başlat menüsündeki daha fazla uygulama kur kdeinit hatası veriyor
![screenshot_20160312_155654](https://cloud.githubusercontent.com/assets/2139833/13723426/68152322-e86d-11e5-908d-ab2292bfce92.png)
![screenshot_20160312_155557](https://cloud.githubusercontent.com/assets/2139833/13723427/6e6671d6-e86d-11e5-97f5-299484179e2f.png)

**Comment by hrngultekin** [comment]
*.desktop  dosyalarında "X-DBUS-StartupType=true" olan satır "X-DBUS-StartupType=false" ile değiştirilerek hata mesajı engellendi
