### ISSUE TITLE
periodic update

### ISSUE THREAD

**Issue by suvari** [PisiLinuxNew/package-manager#9]
package-manager,  ayarlardaki, "enable periodic update check" seçili olmadığı halde, düzenli güncelleme yapmaya çalışıyor
şifre girilmesini istiyor.

**Comment by suvari** [comment]
http://i.hizliresim.com/g8BBG5.png

**Comment by mthnzbk** [comment]
https://github.com/PisiLinuxNew/package-manager/commit/14f834ee3ae65be5d3e2f193d264f9e6c7baa202 ile çözülmüş olması lazım. Deneyip duruma göre kapatırsın abi. Tabi önce güncellemesini alman lazım.

**Comment by mthnzbk** [comment]
Son güncelleme ile 2dk süre ayarlayıp test ettim güncelleme isteğinde bulunmadı.
